from typing import Dict, List, Optional
import json
from datetime import datetime
from state import AgentState, AnnualData

class ReportGenerationAgent:
    """Agent to generate audit reports and visualizations"""

    def __init__(self):
        self.report_template = self._get_report_template()

    def _get_report_template(self) -> str:
        """Get the report template"""
        return """
# Financial Audit Report

## Overview
- **Generated Date**: {generated_date}
- **Audit Period**: {audit_years}
- **Company Health**: {overall_health}
- **Intent**: {intent}

## Executive Summary
{executive_summary}

## Financial Analysis

### Balance Sheet Analysis
{balance_sheet_analysis}

### Income Statement Analysis
{income_analysis}

### Cash Flow Analysis
{cash_flow_analysis}

### Key Financial Ratios
{financial_ratios}

## Trend Analysis
{trend_analysis}

## Risk Assessment
{risk_assessment}

## Recommendations
{recommendations}

## Data Validation
{data_validation}

---
*This report was automatically generated by the Sentient Audit System*
"""

    def format_currency(self, amount: float) -> str:
        """Format currency with proper units"""
        if abs(amount) >= 1_000_000:
            return f"${amount/1_000_000:.2f}M"
        elif abs(amount) >= 1_000:
            return f"${amount/1_000:.2f}K"
        else:
            return f"${amount:,.2f}"

    def generate_executive_summary(self, state: AgentState) -> str:
        """Generate executive summary"""
        if not state.financial_data:
            return "No financial data available for analysis."

        latest_year = max(data.year for data in state.financial_data)
        latest = next(data for data in state.financial_data if data.year == latest_year)

        summary = f"""
The company has shown {'positive' if latest.net_profit > 0 else 'concerning'} financial performance in {latest_year}.
Total assets stand at {self.format_currency(latest.assets)}, with equity of {self.format_currency(latest.equity)}.
The company appears to be in a {state.get_audit_years()[-1] - latest_year + 1}-year trend of {'growth' if latest.revenue > 1_000_000 else 'stability'}.
"""

        # Add anomaly warnings
        if hasattr(state, 'analysis_metrics') and state.analysis_metrics.get('anomalies'):
            anomaly_count = len(state.analysis_metrics['anomalies'])
            summary += f"\n⚠️  {anomaly_count} anomalies detected requiring attention.\n"

        return summary

    def generate_balance_sheet_analysis(self, state: AgentState) -> str:
        """Generate balance sheet analysis"""
        if not state.financial_data:
            return "No balance sheet data available."

        analysis = []
        for data in sorted(state.financial_data, key=lambda x: x.year):
            growth = 0
            if len([d for d in state.financial_data if d.year < data.year]) > 0:
                prev = max([d for d in state.financial_data if d.year < data.year], key=lambda x: x.year)
                growth = ((data.assets - prev.assets) / prev.assets) * 100 if prev.assets > 0 else 0

            analysis.append(f"""
**{data.year}**:
- Total Assets: {self.format_currency(data.assets)}
- Liabilities: {self.format_currency(data.liabilities)}
- Equity: {self.format_currency(data.equity)}
- Asset Growth: {growth:+.1f}%
""")

        return "\n".join(analysis)

    def generate_income_analysis(self, state: AgentState) -> str:
        """Generate income statement analysis"""
        if not state.financial_data:
            return "No income statement data available."

        analysis = []
        for data in sorted(state.financial_data, key=lambda x: x.year):
            margin = (data.net_profit / data.revenue) * 100 if data.revenue > 0 else 0

            analysis.append(f"""
**{data.year}**:
- Revenue: {self.format_currency(data.revenue)}
- Net Profit: {self.format_currency(data.net_profit)}
- Profit Margin: {margin:.1f}%
""")

        return "\n".join(analysis)

    def generate_cash_flow_analysis(self, state: AgentState) -> str:
        """Generate cash flow analysis"""
        if not state.financial_data:
            return "No cash flow data available."

        analysis = []
        for data in sorted(state.financial_data, key=lambda x: x.year):
            # Calculate cash flow to net profit ratio
            ratio = (data.cash_flow / data.net_profit) * 100 if data.net_profit != 0 else 0

            analysis.append(f"""
**{data.year}**:
- Operating Cash Flow: {self.format_currency(data.cash_flow)}
- Cash Flow/Net Profit Ratio: {ratio:.1f}%
""")

        return "\n".join(analysis)

    def generate_financial_ratios(self, state: AgentState) -> str:
        """Generate financial ratios table"""
        if not state.financial_data:
            return "No financial data available for ratio analysis."

        from .financial_agent import FinancialDataAgent
        financial_agent = FinancialDataAgent()
        ratios_by_year = {}

        for data in state.financial_data:
            ratios = financial_agent.calculate_financial_ratios(data)
            ratios_by_year[data.year] = ratios

        # Format as markdown table
        table = "| Year | Current Ratio | Profit Margin | ROE | Asset Turnover | Debt/Equity |\n"
        table += "|------|-------------|--------------|-----|---------------|-------------|\n"

        for year in sorted(ratios_by_year.keys()):
            ratios = ratios_by_year[year]
            table += f"| {year} | {ratios['current_ratio']:.2f} | {ratios['profit_margin']:.1f}% | {ratios['return_on_equity']:.1f}% | {ratios['asset_turnover']:.2f} | {ratios['debt_to_equity']:.2f} |\n"

        return table

    def generate_trend_analysis(self, state: AgentState) -> str:
        """Generate trend analysis"""
        if not state.financial_data or not hasattr(state, 'analysis_metrics'):
            return "No trend data available."

        trends = state.analysis_metrics.get('trends', {})
        analysis = []

        for metric, trend_data in trends.items():
            if 'avg_growth' in trend_data:
                direction = trend_data.get('trend_direction', 'stable')
                avg_growth = trend_data['avg_growth']

                analysis.append(f"""
**{metric.replace('_', ' ').title()}**:
- Average Annual Growth: {avg_growth:+.1f}%
- Trend Direction: {direction.upper()}
""")

        return "\n".join(analysis) if analysis else "No significant trends detected."

    def generate_risk_assessment(self, state: AgentState) -> str:
        """Generate risk assessment"""
        risks = []

        # Check for anomalies
        if hasattr(state, 'analysis_metrics') and state.analysis_metrics.get('anomalies'):
            for anomaly in state.analysis_metrics['anomalies']:
                risks.append(f"- **{anomaly['type'].replace('_', ' ').title()}**: Detected in {anomaly['year']} (Severity: {anomaly['severity'].upper()})")

        # Check financial health
        if hasattr(state, 'analysis_metrics') and state.analysis_metrics.get('health'):
            health = state.analysis_metrics['health']
            poor_indicators = [k for k, v in health.items() if v == 'poor' and k != 'overall']
            if poor_indicators:
                risks.append(f"- **Weak Financial Health**: Poor performance in {', '.join(poor_indicators)}")

        if not risks:
            risks = ["- No significant risks detected based on current data."]

        return "\n".join(risks)

    def generate_recommendations(self, state: AgentState) -> str:
        """Generate actionable recommendations"""
        recommendations = []

        # General recommendations based on financial health
        if hasattr(state, 'analysis_metrics') and state.analysis_metrics.get('health'):
            health = state.analysis_metrics['health']
            overall = health.get('overall', 'unknown')

            if overall == 'poor':
                recommendations.extend([
                    "1. Consider cost reduction strategies to improve profitability",
                    "2. Review debt structure and consider refinancing options",
                    "3. Implement cash flow management improvements"
                ])
            elif overall == 'fair':
                recommendations.extend([
                    "1. Focus on revenue growth initiatives",
                    "2. Monitor key financial metrics closely",
                    "3. Consider optimizing asset utilization"
                ])
            else:
                recommendations.extend([
                    "1. Maintain current growth momentum",
                    "2. Explore new market opportunities",
                    "3. Consider strategic investments for future growth"
                ])

        # Add anomaly-specific recommendations
        if hasattr(state, 'analysis_metrics') and state.analysis_metrics.get('anomalies'):
            recommendations.append("\n**Immediate Actions Required:**")
            for anomaly in state.analysis_metrics['anomalies']:
                if anomaly['type'] == 'extreme_growth':
                    recommendations.append(f"- Investigate unusual {anomaly['metric']} growth in {anomaly['year']}")
                elif anomaly['type'] == 'negative_equity':
                    recommendations.append(f"- Address negative equity position in {anomaly['year']}")

        return "\n".join(recommendations) if recommendations else "No specific recommendations at this time."

    def generate_data_validation(self, state: AgentState) -> str:
        """Generate data validation report"""
        validation_results = state.validate_financial_data()

        if not validation_results:
            return "✅ All financial data passed validation checks."

        validation_report = "⚠️  Validation Issues Found:\n"
        for error in validation_results:
            validation_report += f"- {error}\n"

        return validation_report

    def generate_report(self, state: AgentState) -> str:
        """Generate complete audit report"""
        state.add_log("Generating audit report...")

        # Populate template
        report = self.report_template.format(
            generated_date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            audit_years=", ".join(map(str, state.get_audit_years())),
            overall_health=state.analysis_metrics.get('health', {}).get('overall', 'unknown').upper() if hasattr(state, 'analysis_metrics') else 'UNKNOWN',
            intent=state.intent or "Financial Analysis",
            executive_summary=self.generate_executive_summary(state),
            balance_sheet_analysis=self.generate_balance_sheet_analysis(state),
            income_analysis=self.generate_income_analysis(state),
            cash_flow_analysis=self.generate_cash_flow_analysis(state),
            financial_ratios=self.generate_financial_ratios(state),
            trend_analysis=self.generate_trend_analysis(state),
            risk_assessment=self.generate_risk_assessment(state),
            recommendations=self.generate_recommendations(state),
            data_validation=self.generate_data_validation(state)
        )

        state.add_log("Report generation completed")
        return report

    def process(self, state: AgentState) -> AgentState:
        """Process report generation"""
        if not state.financial_data:
            state.add_log("ERROR: No financial data available for report generation")
            return state

        # Generate the report
        report = self.generate_report(state)

        # Store report in state
        state.report = report  # We'll need to add this field to AgentState later

        state.add_log(f"Generated report with {len(report)} characters")
        return state